version: "3.8"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: vulnops
      POSTGRES_USER: vulnops
      POSTGRES_PASSWORD: vulnops_db_pass_2024
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vulnops"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://vulnops:vulnops_db_pass_2024@db:5432/vulnops
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=django-insecure-vop2x8f4qm7kj9w1nt5rce6yhb3gds0a
      - DEBUG=True
      - ALLOWED_HOSTS=*
      - CORS_ALLOW_ALL_ORIGINS=True
      - ENRICHMENT_API_URL=http://mock-enrichment-api:9003
      - WEBHOOK_RECEIVER_URL=http://mock-webhook-receiver:9002
      - MAIL_SERVICE_URL=http://mock-mail:9001
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    entrypoint: []
    command: celery -A vulnops worker -l info -Q default,reports,imports,webhooks,notifications
    environment:
      - DATABASE_URL=postgresql://vulnops:vulnops_db_pass_2024@db:5432/vulnops
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=django-insecure-vop2x8f4qm7kj9w1nt5rce6yhb3gds0a
      - DEBUG=True
      - ENRICHMENT_API_URL=http://mock-enrichment-api:9003
      - WEBHOOK_RECEIVER_URL=http://mock-webhook-receiver:9002
      - MAIL_SERVICE_URL=http://mock-mail:9001
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8080/api

  proxy:
    image: nginx:1.25-alpine
    ports:
      - "8080:80"
    depends_on:
      - backend
      - frontend

  mock-mail:
    build:
      context: ./mock-services/mail
      dockerfile: Dockerfile
    ports:
      - "9001:9001"

  mock-webhook-receiver:
    build:
      context: ./mock-services/webhook-receiver
      dockerfile: Dockerfile
    ports:
      - "9002:9002"

  mock-enrichment-api:
    build:
      context: ./mock-services/enrichment-api
      dockerfile: Dockerfile
    ports:
      - "9003:9003"

