
worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server_tokens on;

    sendfile on;
    keepalive_timeout 65;
    client_max_body_size 50m;
    resolver 127.0.0.11 valid=10s;

    upstream backend {
        server backend:8000 resolve;
    }

    upstream frontend {
        server frontend:3000 resolve;
    }

    server {
        listen 80;
        server_name _;

        add_header Access-Control-Allow-Origin * always;
        add_header Access-Control-Allow-Methods "GET, POST, PUT, PATCH, DELETE, OPTIONS, TRACE" always;
        add_header Access-Control-Allow-Headers * always;
        add_header Access-Control-Allow-Credentials true always;

        add_header X-Debug-Mode "enabled" always;
        add_header X-Powered-By "VulnOps/2.0 Django/4.2" always;

        location /api/ {
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /admin/ {
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /health/ {
            proxy_pass http://backend;
        }

        location /ready/ {
            proxy_pass http://backend;
        }

        location /media/ {
            alias /media/;
            autoindex on;
            expires 1d;
        }

        location /static/ {
            alias /static/;
            expires 7d;
        }

        location /nginx-status {
            stub_status on;
            allow all;
        }

        location / {
            proxy_pass http://frontend;
            proxy_set_header Host $host;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}
